# Generated by Django 3.1.7 on 2021-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Flavien Chamay', editable=False, max_length=200),
        ),
    ]
