# Generated by Django 3.1.7 on 2021-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Flavien Chamay', max_length=200),
        ),
    ]
